---

plugins:
  - jest
  - babel

env:
  browser: true
  jest: true
  es6: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parser: babel-eslint

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  no-console: 0
