name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: make install
        env:
          CI: true
      - name: Run linter
        run: make lint
