name: Lint

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: make install
        env:
          CI: true
      - name: Run linter
        run: make lint
